=== seweu/naxos-info/src/naxos-content.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="seite" type="seite"/>

	<xs:simpleType name="beschreibungTyp">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="bild"/>
	    <xs:enumeration value="text"/>
	  </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lang">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="de"/>
	    <xs:enumeration value="en"/>
	  </xs:restriction>
	</xs:simpleType>	

	<xs:complexType name="titel">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="lang" type="lang" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="verweise">
		<xs:sequence>
			<xs:element name="verweis" type="verweis" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="verweis">
		<xs:attribute name="typ" type="xs:string" use="optional"/>
		<xs:attribute name="lang" type="lang" use="optional"/>
		<xs:attribute name="ziel" type="xs:string" use="required"/>
		<xs:attribute name="titel" type="xs:string" use="required"/>
		<xs:attribute name="beschreibung" type="xs:string" use="optional"/>	
	</xs:complexType>

	<xs:complexType name="preis" mixed="true">
		<xs:attribute name="lang" type="lang" use="optional"/>
	</xs:complexType>

	<xs:complexType name="seite">
		<xs:sequence>
			<xs:element name="titel" type="titel" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="beschreibung" type="beschreibung" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="verweise" type="verweise" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="verweis" type="verweis" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="preis" type="preis" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>	  
		<xs:attribute name="typ" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="beschreibung" mixed="true">
		<xs:sequence >
			<xs:element name="verweis" type="verweis" minOccurs="0"/>
			<xs:element name="span" type="span" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="br" type="br" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="typ" type="beschreibungTyp" use="required"/>
		<xs:attribute name="src" type="xs:string" use="optional"/>
		<xs:attribute name="lang" type="lang" use="optional"/>
	</xs:complexType>	
	
	<xs:complexType name="br"/>
	
	<xs:complexType name="span">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="class" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/aegean_palace.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Aegean Palace (Drei Brüder)</titel>
	<titel lang="en">Aegean Palace (Drei Brüder)</titel>
	<beschreibung typ="bild" src="images/aegean_palace/aegean5.jpg"/>
	<beschreibung typ="bild" src="images/aegean_palace/aegean3.jpg"/>
	<beschreibung typ="text" lang="de">
		Seit Jahren arbeiten wir mit den beiden Häusern der 3 Brüder zusammen. 
		Noch nie ist ein Gast hier abgereist, der nicht zufrieden war...
	</beschreibung>
	<beschreibung typ="text" lang="en">
		Many years now we successfully work with the 2 smaller hotels of the 3 brothers.
		Never one of our guests was not happy with his stay there.
	</beschreibung>	
	<beschreibung typ="text" lang="de">
		In diesem Jahr hat die Familie ein Hotel eröffnet, das nun an der Plaka sicherlich die 1. Adresse ist. 
		Es ist ihnen gelungen hinter der netten Kykladenarchitektur ein Hotel der Extraklasse zu verstecken. 
		Die typische Bebauung der Plaka ist nicht durch einen Hotelpalast zerstört wurden.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		This year the family opened a hotel which surely is the No. 1 now in Plaka.
		They managed to keep the traditional Cycladic architecture and "hide" a 1st class hotel inside. 
		The wonderful Plaka did not get destroyed by a huge hotel complex.
	</beschreibung>		
	<beschreibung typ="text" lang="de">
		Hier gönnen Sie sich das Besondere. Den schönsten Strand der Insel verbunden mit dem bisschen "Mehr an Komfort". 
		Es wird Ihnen an nichts fehlen. Unnötig hier alle Vorzüge aufzulisten.
		Es ist alles da... Vom Schwimmbad bis zur Sauna. Von der 24 Std.Rezeption bis zum Konferenzraum.			
	</beschreibung>
	<beschreibung typ="text" lang="en">
		Here you will treat yourself to something special. The most beautiful beach on the island in combination with the little extra in comfort.
		It is useless to give a list of everything you will find.
		You simply will not miss anything! From the big pool to a sauna, from a 24 h reception to conference rooms.
	</beschreibung>	
	<beschreibung typ="bild" src="images/aegean_palace/aegean2.jpg"/>
	<beschreibung typ="bild" src="images/aegean_palace/aegean6.jpg"/>
	<beschreibung typ="text" lang="de">
		Wie die Taverne der 3 Brüder liegt das Hotel direkt am Plakastrand und nur 100  Meter vom Meer entfernt. 
		Der Sandstrand erinnert mit seinen Dünen an die Inseln der Nordsee und das Wasser fällt langsam ab. 
		So sind auch Kinder hier besonders gut aufgehoben.
	</beschreibung>
	<beschreibung typ="text" lang="en">	
		Like the 3 brothers restaurant the hotel is direct at Plaka beach and only 100 m from the most beautiful water. 
		The white sandy beach falls only slowly into the water - so children are safe.
	</beschreibung>
	<preis lang="de">
		EZ in der Vorsaison 65 &#x20AC; / Zwischensaison &#x20AC; 95 / Hochsaison &#x20AC; 150
	</preis>
	<preis lang="en">
		Single out of season &#x20AC; 65 - middle &#x20AC; 95 - high &#x20AC; 150
	</preis>
	<preis lang="de">
		DZ in der Vorsaison 75 &#x20AC; / Zwischensaison &#x20AC; 120 / Hochsaison &#x20AC; 185
	</preis>
	<preis lang="en">
		Double out of season &#x20AC; 75 - middle &#x20AC; 120 - high &#x20AC; 185
	</preis>
	<preis lang="de">
		Appartment (2-Raum) in der Vorsaison 95 &#x20AC; / Zwischensaison &#x20AC; 220 / Hochsaison &#x20AC; 300
	</preis>
	<preis lang="en">
		Appartment (2-rooms) out of season &#x20AC; 95 - middle &#x20AC; 220 - high &#x20AC; 300
	</preis>		
	<preis lang="de">
		Suite zwischen &#x20AC; 90 und &#x20AC; 300
	</preis>
	<preis lang="en">
		Suite between &#x20AC; 90 and &#x20AC; 300
	</preis>		
	<preis lang="de">
		Das Frühstücksbuffet ist inkl.
	</preis>
	<preis lang="en">
		Breakfast included
	</preis>	
</seite>

=== seweu/naxos-info/src/hausverwaltung.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="allgemein" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="naxos-content.xsd">
	<titel lang="de">Wir betreuen Ihr Haus durchgängig das ganze Jahr</titel>
	<titel lang="en">We take care of your house throughout the whole year...</titel>

	<beschreibung typ="text" lang="de">- Reinigungsdienst</beschreibung>
	<beschreibung typ="text" lang="de">- Gartenpflege</beschreibung>
	<beschreibung typ="text" lang="de">- qualifizierte Umbauten</beschreibung>
	<beschreibung typ="text" lang="de">- Bauaufsicht</beschreibung>
	<beschreibung typ="text" lang="de">- u.v.m.</beschreibung>

	<beschreibung typ="text" lang="en">- Cleaning</beschreibung>
	<beschreibung typ="text" lang="en">- Gardening</beschreibung>
	<beschreibung typ="text" lang="en">- Qualified Conversion</beschreibung>
	<beschreibung typ="text" lang="en">- Building Supervision</beschreibung>
	<beschreibung typ="text" lang="en">- and much more...</beschreibung>

	<verweis typ="bottom" lang="de" ziel="de/unterkuenfte.xml" titel="eben genau so, wie Sie es sich vorstellen ..."/>
	<verweis typ="bottom" lang="en" ziel="en/unterkuenfte.xml" titel="just like  you imagine it to be..."/>

</seite>

=== seweu/naxos-info/src/einleitung.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="allgemein" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="naxos-content.xsd">

	<beschreibung typ="text" lang="de">Naxos - die wunderschöne Kykladeninsel in Griechenland</beschreibung>
	<beschreibung typ="text" lang="de">mit belebten oder einsamen Stränden</beschreibung>
	<beschreibung typ="text" lang="de">mit freundlichen Gastgebern und netten Individualtouristen</beschreibung>
	<beschreibung typ="text" lang="de">mit Bergen und herrlichen Wanderwegen</beschreibung>
	<beschreibung typ="text" lang="de">mit grünen Tälern und klaren Flüssen</beschreibung>
	<beschreibung typ="text" lang="de">Ein Paradies</beschreibung>
	<beschreibung typ="text" lang="de">zum Faulenzen und Spaß haben</beschreibung>
	<beschreibung typ="text" lang="de">zum Schwimmen und Wandern</beschreibung>
	<beschreibung typ="text" lang="de">zum Surfen und Mountain-Biken</beschreibung>
	<beschreibung typ="text" lang="de">zum Segeln u.s.v.m.</beschreibung>
	
	<beschreibung typ="text" lang="en">Naxos - one of the most beautiful islands in the Greek Cyclades</beschreibung>
	<beschreibung typ="text" lang="en">with solitary sands or lively, sun-drenched beaches,</beschreibung>
	<beschreibung typ="text" lang="en">friendly, helpful locals and tourists alike,</beschreibung>
	<beschreibung typ="text" lang="en">with breath-taking mountains, idyllic seasides,</beschreibung>
	<beschreibung typ="text" lang="en">green valleys and clear rivers.</beschreibung>
	<beschreibung typ="text" lang="en">A paradise in which you can</beschreibung>
	<beschreibung typ="text" lang="en">either just relax,</beschreibung>
	<beschreibung typ="text" lang="en">or enjoy swimming, hiking, surfing, sailing or mountain biking...</beschreibung>

	<verweis typ="bottom" lang="de" ziel="unterkuenfte.xml" titel="eben genau so, wie Sie es sich vorstellen ..."/>
	<verweis typ="bottom" lang="en" ziel="unterkuenfte.xml" titel="... just as you imagined it in your dreams"/>

</seite>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/niko.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Hotel Niko</titel>
	<beschreibung typ="bild" src="images/niko/plakaniko.jpg"/>
	<beschreibung typ="bild" src="images/niko/plakaniko2.jpg"/>
	<beschreibung typ="text" lang="de">
		Die Studios und die angeschlossene Taverne von Niko und Maria liegen direkt 
		am Strand der Plaka und sind nur 20 Meter vom Meer entfernt. 
		Hier ist der Sandstrand ganz besonders schön und lediglich 
		in den Monaten Juli und August gut besucht. In meinen Augen 
		(feiner Sand, wenig Leute, Dünen wie an der Nordsee...) der schönste Strandabschnitt.		
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The studios and the taverna of Niko and Maria are right at the beach and only 20 m away from the water.
		Here the sandy beach is specially beautiful and only well visited in jul/aug.
		In my eyes this part of Plaka beach is the nicest. Fine sand, dunes, few people...	
	</beschreibung>	
	<preis lang="de">
		 Die Studios (Doppelzimmer mit Küche, Bad und Balkon/Terrasse) liegen 
		- je nach Reisezeit und Lage - zwischen &#x20AC; 40 - 65. 
		Lediglich Ende Juli und August liegen die Preise bei &#x20AC; 70 - 75. 
		2 Zimmer-Appartements mit Bad, Küche und großer Terrasse für 4 Personen 
		&#x20AC; 50 - 75 und im Juli/August &#x20AC; 83 - 110 
	</preis>
	<preis lang="en">
		The studios will be - depending on traveling time - between &#x20AC; 40-65. 
		Jul/aug &#x20AC; 70-75.
		Apartments with two rooms &#x20AC; 50 - 75. Jul+Aug 83 - 110	
	</preis>
</seite>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/morgana.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Villa Morgana</titel>
	<titel lang="en">Villa Morgana</titel>
	<beschreibung typ="bild" src="images/morgana/morgana1.jpg"/>
	<beschreibung typ="bild" src="images/morgana/morgana2.jpg"/>
	<beschreibung typ="text" lang="de">
		Für den anspruchsvollen Gast ist gleich an dem schönsten Strandabschnitt der Plaka etwas ganz Besonderes entstanden. 
		Die Villa Morgana liegt völlig ruhig nur 20 Meter vom Wasser entfernt. 
		Im Haus gibt es nur 4 Wohnungen. 2 große 1-Zimmer Appartements 
		mit Küche für 2-3 Personen und 2 große 2-Zimmer-Appartements für 4-5 Personen.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		For our guests who expect the "little something more" the most beautiful Plaka beach offers a great new place.
		The Villa Morgana lies totally quiet and peaceful only 20 m away from the sea. 
		The house has only two big apartments with 2 double rooms for 4-5 persons and 2 smaller ones for 2-3 persons.
	</beschreibung>
	<beschreibung typ="bild" src="images/morgana/morgana3.jpg"/>
	<beschreibung typ="bild" src="images/morgana/morgana4.jpg"/>
	<beschreibung typ="text" lang="de">
        Wir haben selten ein Haus gesehen, das mit so viel Liebe und Geschmack eingerichtet wurde und in dem an Ausstattung und Komfort 
        wirklich keine Wünsche offen bleiben. Der Service ist einmalig und die tägliche Reinigung eine Selbstverständlichkeit.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		We rarely saw a house which was furnished with so much love and taste.
		It is comfortable and convenient that all your wishes should be fulfilled.
		The service is great and daily cleaning goes without saying.
	</beschreibung>		
	<preis lang="de">
		Komfort hat allerdings auch in Griechenland seinen Preis.
		Die kleinen Wohnungen im Parterre kosten - je nach Saison - 
		zwischen &#x20AC; 90 und &#x20AC; 160/Tag.
		Die großen Wohnungen für 4-5 Personen im 1. Stock zwischen &#x20AC; 150 und &#x20AC; 230/Tag. 
		Den grandiosen Meerblick bieten alle vier Wohnungen.	
	</preis>
	<preis lang="en">
		Even in Greece such comfort has obviously its price. 
		The small apartment will be - depending on the time of year - between &#x20AC; 90-160 and the 2-room apartment between &#x20AC; 150-230/day.
	</preis>
</seite>
