=== seweu/naxos-info/src/naxos-content.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="seite" type="seite"/>

	<xs:simpleType name="beschreibungTyp">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="bild"/>
	    <xs:enumeration value="text"/>
	  </xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="lang">
	  <xs:restriction base="xs:string">
	    <xs:enumeration value="de"/>
	    <xs:enumeration value="en"/>
	  </xs:restriction>
	</xs:simpleType>	

	<xs:complexType name="titel">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="lang" type="lang" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="verweise">
		<xs:sequence>
			<xs:element name="verweis" type="verweis" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="verweis">
		<xs:attribute name="typ" type="xs:string" use="optional"/>
		<xs:attribute name="lang" type="lang" use="optional"/>
		<xs:attribute name="ziel" type="xs:string" use="required"/>
		<xs:attribute name="titel" type="xs:string" use="required"/>
		<xs:attribute name="beschreibung" type="xs:string" use="optional"/>	
	</xs:complexType>

	<xs:complexType name="preis" mixed="true">
		<xs:attribute name="lang" type="lang" use="optional"/>
	</xs:complexType>

	<xs:complexType name="seite">
		<xs:sequence>
			<xs:element name="titel" type="titel" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="beschreibung" type="beschreibung" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="verweise" type="verweise" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="verweis" type="verweis" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="preis" type="preis" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>	  
		<xs:attribute name="typ" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="beschreibung" mixed="true">
		<xs:sequence >
			<xs:element name="verweis" type="verweis" minOccurs="0"/>
			<xs:element name="span" type="span" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="br" type="br" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="typ" type="beschreibungTyp" use="required"/>
		<xs:attribute name="src" type="xs:string" use="optional"/>
		<xs:attribute name="lang" type="lang" use="optional"/>
	</xs:complexType>	
	
	<xs:complexType name="br"/>
	
	<xs:complexType name="span">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="class" type="xs:string" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

</xs:schema>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/hausplaka.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Villa Kazilieris</titel>
	<titel lang="en">Villa Kazilieris</titel>
	<beschreibung typ="bild" src="images/hausplaka/jakob_aussen.jpg"/>
	<beschreibung typ="bild" src="images/hausplaka/jakob_innen.jpg"/>
	<beschreibung typ="text" lang="de">
		Dieses private Ferienhaus für 6 Personen (und ggf. 2 Kinder) liegt hoch über dem Strand der Plaka. 
		Der unverbaute Blick eröffnet von den verschiedenen Terrassen einen sagenhaften Blick zum Meer und in die Berge.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		This private summer cottage for 6 persons (and maybe 2 children) you will find above Plaka beach. 
		The unobstructed view from the different terraces opens an incredible look down to the sea and into the mountains.
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Der windgeschützte Innenhof läd zum Träumen ein ...
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The sheltered courtyard invites you to stay and dream ...
	</beschreibung>			
	<beschreibung typ="bild" src="images/hausplaka/jakob_haengematte.jpg"/>
	<beschreibung typ="bild" src="images/hausplaka/jakob_terrasse.jpg"/>
	<beschreibung typ="text" lang="de">
		... und eigentlich könnte man auch gleich hier oben bleiben und den Trubel der Welt vergessen.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		... and, actually, one could also remain up here and forget the rest of the world.
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Das Haus verfügt über 3 Schlafzimmer, zwei Bäder, ein wunderschönes Wohnzimmer mit großer Küche, Innenhof, Terrassen u.v.m .
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The house has 3 bedrooms with a private bath each, a wonderful sitting room with big kitchen, inner courtyard, terraces ...
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Dieser Platz ist ideal geeignet für Menschen, die einfach mal ihre Ruhe haben wollen. Das Ausleihen eines kleines Jeeps ist jedoch empfohlen, 
        da der kürzeste Weg runter zum Meer nicht weit aber etwas holprig ist.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The house is suited ideally for people who simply want to have their peace and quiet.
		Nevertheless, the borrowing of a small jeep is recommended, because the road down to the sea is not far but a little rough.
	</beschreibung>		
	<preis lang="de">
		 Je nach Reisezeit und Aufenthaltsdauer kostet das Haus pro Tag zwischen &#x20AC; 120 und &#x20AC; 150. 
	</preis>
	<preis lang="en">
		According to holiday season and duration of your stay the rent will be between &#x20AC; 120 and &#x20AC; 150/day.
	</preis>
	<preis lang="de">
		 Endreinigung inkl. Wäsche &#x20AC; 130 
	</preis>	
	<preis lang="en">
		Cleaning incl. sheets, towels etc. &#x20AC; 130	
	</preis>	
</seite>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/rainer.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Plaka Ferienhaus III (zu verkaufen)</titel>
	<titel lang="en">Plaka Ferienhaus III (for sale)</titel>
	<beschreibung typ="bild" src="images/rainer/rainer1.jpg"/>
	<beschreibung typ="bild" src="images/rainer/rainer2.jpg"/>
	<beschreibung typ="text" lang="de">
		Oberhalb der Plaka steht dieses einmalige, private Landhaus. 
		Von diesem Grundstück ist der "Rundumblick" über das Meer zu den Inseln, 
		die Stadt Naxos und die Berge ungehindert möglich. Wer wirklich abschalten will 
		und die ungestörte Ruhe und Entspannung sucht, ist hier genau richtig.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		Above Plaka Beach you will find this unique private cottage. 
		From this location you have a nice view down to the sea, to Naxos town and into the mountains. 
		If you really want to take your mind off everything and you are searching real peace, this is your place.
	</beschreibung>
	<beschreibung typ="bild" src="images/rainer/rainer3.jpg"/>
	<beschreibung typ="bild" src="images/rainer/rainer4.jpg"/>	
	<beschreibung typ="text" lang="de">
		Fernab von den Lichtern der Stadt öffnet sich nachts der Himmel mit all seinen Sternen 
		und sogar die Milchstraße ist zu sehen...
	</beschreibung>
	<beschreibung typ="text" lang="en">
		At night and away from the lights of the town you can see and enjoy the million stars...
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Das Haus verfügt über 3 Doppelzimmer, 1 EZ, einen großen Wohnraum mit Kamin, mehrere Terrassen, 
		einen Dachgarten und ein 3500 m2 großes Grundstück mit Weingarten. Eine große Familie 
		oder 3 Paare können hier leicht gemeinsam Urlaub machen. Das Haus verfügt über 3 Doppelzimmer, 
		1 EZ, einen großen Wohnraum mit Kamin, mehrere Terrassen, 
		einen Dachgarten und ein 3500 m2 großes Grundstück mit Weingarten. 
		Eine große Familie oder 3 Paare können hier leicht gemeinsam Urlaub machen.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The house has 3 double rooms, 2 bathrooms, a big livingroom with a fire place, several terraces and a 3500 m2 garden with a vineyard.
		A large family or 3 couples can easily spent their holiday together.
	</beschreibung>
	<beschreibung typ="bild" src="images/rainer/rainer5.jpg"/>	
	<beschreibung typ="text" lang="de">
		Eine solch ungestörte Ruhe findet sich nicht an der "Bushaltestelle". 
		Das Ausleihen eines robusten Wagens ist daher empfehlenswert.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		Such peace and silence you will not find next to a "busstop". We suggest to rent a tough little car.
	</beschreibung>				
	<preis lang="de">
		 Der Mietpreis für dieses Haus beträgt &#x20AC; 140 - 180/Tag 
	</preis>
	<preis lang="en">
		The rent will be &#x20AC; 140 - 180/day.
	</preis>
	<preis lang="de">
		 Endreinigung inkl. Wäsche &#x20AC; 150 
	</preis>	
	<preis lang="en">
		Cleaning incl. sheets, towels etc. &#x20AC; 150	
	</preis>	
</seite>

=== seweu/naxos-info/src/service.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="allgemein" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="naxos-content.xsd">
	<beschreibung typ="text" lang="de">- Wir helfen bei der Planung oder Buchung der <span class="fett">Anreise</span></beschreibung>
	<beschreibung typ="text" lang="de">- Wir holen Sie am <span class="fett">Hafen</span> (oder Flughafen) ab</beschreibung>
	<beschreibung typ="text" lang="de">- Wir zeigen Ihnen die <span class="fett">schönsten Ecken</span> der Insel</beschreibung>
	<beschreibung typ="text" lang="de">- Wir besorgen Ihnen den geeigneten <span class="fett">Wanderführer</span></beschreibung>
	<beschreibung typ="text" lang="de">- Wir buchen Ihr <span class="fett">Mountainbike, Motorrad</span> oder Ihren <span class="fett">Mietwagen</span></beschreibung>
	<beschreibung typ="text" lang="de">- Wir vermitteln Ihnen einen traumhaften <span class="fett">Segeltörn</span> oder einen <span class="fett">Surfkurs</span><br/><br/></beschreibung>
	<beschreibung typ="text" lang="de">- <span class="fett">Wir sind da - wann immer Sie uns brauchen ...</span><br/><br/></beschreibung>
	<beschreibung typ="text" lang="de">... und falls Sie sich in die Insel verlieben, suchen wir mit Ihnen Ihr <verweis ziel="../hausverkauf/a_hausverkauf.htm" titel="Haus oder Traumgrundstück"/></beschreibung>

	<beschreibung typ="text" lang="en">- We help you with the planning or booking of your <span class="fett">jounrney</span></beschreibung>
	<beschreibung typ="text" lang="en">- We pick you up at the <span class="fett">harbour</span> or at the airport</beschreibung>
	<beschreibung typ="text" lang="en">- We show you the <span class="fett">nicest parts</span> of the island</beschreibung>
	<beschreibung typ="text" lang="en">- We choose an experienced <span class="fett">walking-guide</span> for you</beschreibung>
	<beschreibung typ="text" lang="en">- We book your <span class="fett">car, bike</span> or <span class="fett">mountainbike</span></beschreibung>
	<beschreibung typ="text" lang="en">- We arrange a <span class="fett">surf-course</span> or a <span class="fett">sailing-turn</span> for you<br/><br/></beschreibung>
	<beschreibung typ="text" lang="en">- <span class="fett">We are there for your whenever you need us ...</span><br/><br/></beschreibung>
	<beschreibung typ="text" lang="en">... and in case you fall in love with the island, we'll help you to find your <verweis ziel="../hausverkauf/a_hausverkauf.htm" titel="dream place"/></beschreibung>

	<verweis typ="bottom" lang="de" ziel="unterkuenfte.xml" titel="eben genau so, wie Sie es sich vorstellen ..."/>
	<verweis typ="bottom" lang="en" ziel="unterkuenfte.xml" titel="just like  you imagine it to be..."/>

</seite>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/ferienhausIb.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Plaka Ferienhaus Ib</titel>
	<titel lang="en">Plaka Ferienhaus Ib</titel>
	<beschreibung typ="bild" src="images/ferienhausIb/plaka1b.jpg"/>
	<beschreibung typ="text" lang="de">
		Nur 150 m vom Wasser entfernt liegt dieses nette Ferienhaus für 4 Personen. 
		In Kombination mit dem Nachbarhaus (FH Henning) können hier 8 Personen gemütlich 
		Urlaub gemeinsam machen und dennoch Rückzugsmöglichkeiten haben.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		Only 150 m from the most beautiful beach of Plaka you will find this nice little house for 4 persons.
		In combination with the house next door (Plaka I Henning) even 8 persons can spend a phantastic holiday with the private space for everyone.
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Die Tavernen der Plaka sind zu Fuß erreichbar und ein Supermarkt ist ca. 300 m entfernt. 
		Der Bus zum Hafen von Naxos fährt regelmäßig bis an die Plaka und zurück. 
		Noch schöner ist es sicher, wenn man einen kleinen Leihwagen oder ein Moped zur Verfügung hat.
	</beschreibung>	
	<preis lang="de">
		 April + Oktober 90 &#x20AC;
	</preis>
	<preis lang="en">
		April + October &#x20AC; 90 
	</preis>
	<preis lang="de">
		 Juli und August 125 &#x20AC;
	</preis>
	<preis lang="en">
		July and August &#x20AC; 125
	</preis>	
	<preis lang="de">
		 Mai, Juni und September 105 &#x20AC;
	</preis>
	<preis lang="en">
		May, June and September &#x20AC; 105
	</preis>	
	<preis lang="de">
		 Endreinigung inkl. Wäsche &#x20AC; 100 
	</preis>	
	<preis lang="en">
		Cleaning incl. sheets, towels etc. &#x20AC; 100	
	</preis>
</seite>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/katerina.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Agia Anna / Katerina</titel>
	<titel lang="en">Agia Anna / Katerina</titel>
	<beschreibung typ="bild" src="images/katerina/agiakaterina.jpg"/>
	<beschreibung typ="bild" src="images/katerina/agiakaterina2.jpg"/>
	<beschreibung typ="text" lang="de">
		Die Taverne von Katerina und Georgios liegt direkt am Strand von Agia Anna nur 10 Meter vom Wasser entfernt.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The taverna of Katerina and Georgios is right at the seafront of Agia Anna and only 10 m away from the water.
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Diesen Platz empfehle ich besonders Familien mit kleinen Kindern, 
		weil hier das saubere Wasser nur ganz langsam abfällt und Kinder gefahrlos 
		am Strand spielen können. Außerdem können Eltern noch in Ruhe auf der 
		wunderschönen Terrasse sitzen und frühstücken, während die Kinder schon im Sand spielen.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		This beautiful place I specially recomend to parants with children because the beach goes down into the clear water only very slowly.
		The children can play at the beach while their parents are stil having breakfast on the beautiful terrace.
	</beschreibung>
	<beschreibung typ="text" lang="de">
		Auch am Abend kann man in Georgios Restaurant (herrlicher Sonnenuntergangsplatz...) 
		gut sitzen und hervorragend essen. Da die Zimmer direkt über der Taverne liegen, 
		können die "lieben Kleinen" schon schlafen und man ist nah bei ihnen (Babyphon?).
	</beschreibung>
	<beschreibung typ="text" lang="en">
		In the evening you can eat in Georgio's Restaurant and enjoy the sunset over Paros. 
		Because the rooms are right above the terrace the children can be in bed while you stil sit here... (babyphone?)	
	</beschreibung>	
	<beschreibung typ="text" lang="de">
		Das ganze Haus ist außerordentlich sauber und gepflegt und die Familie ist liebenswert und hilfsbereit.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The whole house is very clean and the owners are exceptional friendly and helpful.	
	</beschreibung>
	<preis lang="de">
		 Die Studios (2-3 Bettzimmer mit Bad und Balkon) kosten in der Vor- und Nachsaison, 
		 je nach Reisezeit, zwischen 48 und 63. Lediglich Ende Juli und im August liegen die Preise bei 88. 
		 Die Zweiraumappartements kosten &#x20AC; 55 - 90 und in der Hochsaison dann &#x20AC; 115.
	</preis>
	<preis lang="en">
		Sudios (for 2-3 beds) will be between &#x20AC; 48-63 and &#x20AC; 88 (july/aug), two-room-flat &#x20AC; 55 - 90 and in &#x20AC; 115 (july / aug).
	</preis>
</seite>

=== seweu/naxos-info/src/unterkuenfte.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="allgemein" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="naxos-content.xsd">
	<titel lang="de">
		Wir vermitteln und buchen Unterkünfte für nette Individualtouristen und lustige Kleingruppen
	</titel>
	<titel lang="de">
		Und unser persönlicher Inselservice bietet unseren Gästen das Stückchen Verwöhnung mehr...
	</titel>			
	<titel lang="en">
		We organize the arrangement and booking of your accomodation
	</titel>
	<titel lang="en">
		(mainly for individual tourists and small groups)
	</titel>
	
	<verweise>
	<verweis typ="subfolder" ziel="../unterkuenfte/stadt" titel="Naxos Stadt" beschreibung="(St. George Beach)"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/agia_anna" titel="Agia Anna" beschreibung="(Plaka Beach)"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/prokopios" titel="Ag. Prokopios"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/mikri_vigla" titel="Mikri Vigla"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/tripodes" titel="Tripodes"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/glinado" titel="Glinado"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/motsouna" titel="Motsouna" beschreibung="(Ostküste)"/>
	<verweis typ="subfolder" ziel="../unterkuenfte/landkarte" titel="Landkarte"/>
	</verweise>
	
	<verweis typ="bottom" lang="de" ziel="service.xml" titel="eben genau so, wie Sie es sich vorstellen ..."/>
	<verweis typ="bottom" lang="en" ziel="service.xml" titel="just like  you imagine it to be..."/>


</seite>

=== seweu/naxos-info/src/unterkuenfte/agia_anna/dreibrueder.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<seite typ="unterkunft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../../naxos-content.xsd">
	<titel lang="de">Hotel Drei Brüder</titel>
	<titel lang="en">Hotel Drei Brüder</titel>
	<beschreibung typ="bild" src="images/dreibrueder/dreibrueder1.jpg"/>
	<beschreibung typ="bild" src="images/dreibrueder/dreibrueder2.jpg"/>
	<beschreibung typ="text" lang="de">
		Die Studios und Zimmer dieser Anlage (oben links) mit netter Taverne liegen direkt 
		am Plakastrand und sind nur 50 Meter vom Meer entfernt. 
		Der Sandstrand erinnert mit seinen Dünen an die Inseln der Nordsee 
		und das Wasser fällt langsam ab. So sind auch Kinder hier besonders gut aufgehoben. 
		Noch ruhiger liegt das neue Wohnhaus 200 m von Strand und Taverne entfernt, 
		bietet aber ebenfalls den Blick aufs Meer. (oben rechts)
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The studios and rooms of this plant (above left) and are only 50 meters away from the sea front. 
		The sandy beach reminds of the North Sea with its dunes and the water falls down down only slowly into the sea. 
		So children are safe and comfortable.
	</beschreibung>
	<beschreibung typ="bild" src="images/dreibrueder/dreibrueder3.jpg"/>
	<beschreibung typ="text" lang="de">
		In dieser Anlage kann man sich natürlich selbst versorgen oder man 
		lässt sich in der Taverne verwöhnen. Das Essen ist gut und preiswert 
		und der Ausblick von der Tavernenterrasse sagenhaft schön. 
		Die Zimmer können mit oder ohne Frühstück gebucht werden und sicher 
		gehört die Anlage von Anna und Georgio zu unseren absoluten Lieblingsadressen. 
		Der Service ist sehr gut und die Aufmerksamkeit der Eigentümer einmalig.
	</beschreibung>
	<beschreibung typ="text" lang="en">
		The 4-5 person apartments with 2 separate rooms are located in Georgios plant 200 m away from the beach, however, 
		also offer the view to the sea.(above on the right).
		In this plant you can cook for yourself or you treat yourself in the good tavern with its beautiful view to the sea. 
		Georgios offers a breakfast bufet for his residents and good cooked food all day long.		
	</beschreibung>
	<beschreibung typ="bild" src="images/dreibrueder/dreibrueder4.jpg"/>
	<preis lang="de">
		 Die Studios (Doppelzimmer mit Küche, Bad und Balkon/Terrasse) kosten in der Vor- und Nachsaison &#x20AC; 45 inkl. Frühstück. 
		 In der Zwischensaison &#x20AC; 75 - 90 und in der Hochsaison dann &#x20AC; 110. 
	</preis>
	<preis lang="en">
		The sudios (double rooms with kitchen, bath and balcony/terrace) cost - depending on time of travelling and size - between &#x20AC; 45-90. 
		Merely at the end of July and in August the prices is &#x20AC; 110. 
	</preis>
	<preis lang="de">
		 Die 2-Zimmer-Wohnungen kosten entsprechend &#x20AC; 65 - 120 und in der Hochsaison &#x20AC; 140 (inkl. Frühstück) 
	</preis>
	<preis lang="en">
		The 2 room appartements  cost &#x20AC; 65-120 and in high season &#x20AC; 140 (incl. breakfast) 
		There also are some double rooms. They don't have a kitchen but they are a little cheaper.	
	</preis>
</seite>

=== seweu/naxos-info/src/kontakt.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<seite typ="allgemein" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="naxos-content.xsd">
	<beschreibung typ="text" lang="de">Wir sind das ganze Jahr für Sie per Telefon und Email zu erreichen</beschreibung>
	<beschreibung typ="text" lang="en">You can contact us the whole year by phone, email</beschreibung>	
	<beschreibung typ="text" lang="de"><span class="fett">- Sie stellen eine Aufgabe, wir lösen sie! -</span><br/><br/></beschreibung>
	<beschreibung typ="text" lang="en"><span class="fett">- You set us a task - we solve it! -</span><br/><br/></beschreibung>	
	<beschreibung typ="text">Daniela Martin</beschreibung>
	<beschreibung typ="text">Odos Monis, Chora, GR-84300 Naxos<br/><br/></beschreibung>
	<beschreibung typ="text">e-mail: <verweis ziel="mailto:urlaub@naxosreisen.de" titel="urlaub@naxosreisen.de"/></beschreibung>
	<beschreibung typ="text"><br/>Tel +30 22850 29121</beschreibung>
	<beschreibung typ="text">Mobil +30 694 8853608<br/><br/></beschreibung>
	
	<verweis typ="bottom" lang="de" ziel="#" titel="eben genau so, wie Sie es sich vorstellen !"/>
	<verweis typ="bottom" lang="en" ziel="#" titel="just like  you imagine it to be !"/>
	
</seite>
